# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'MyQtUI1.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1346, 860)
        MainWindow.setStyleSheet("QPalette{background:#FFFFFF;}*{outline:0px;color:#57595B;}\n"
"\n"
"QWidget[form=\"true\"],QLabel[frameShape=\"1\"]{\n"
"border:1px solid #B6B6B6;\n"
"border-radius:0px;\n"
"}\n"
"\n"
"QWidget[form=\"bottom\"]{\n"
"background:#E4E4E4;\n"
"}\n"
"\n"
"QWidget[form=\"bottom\"] .QFrame{\n"
"border:1px solid #57595B;\n"
"}\n"
"\n"
"QWidget[form=\"bottom\"] QLabel,QWidget[form=\"title\"] QLabel{\n"
"border-radius:0px;\n"
"color:#57595B;\n"
"background:none;\n"
"border-style:none;\n"
"}\n"
"\n"
"QWidget[form=\"title\"],QWidget[nav=\"left\"],QWidget[nav=\"top\"] QAbstractButton{\n"
"border-style:none;\n"
"border-radius:0px;\n"
"padding:5px;\n"
"color:#57595B;\n"
"background:qlineargradient(spread:pad,x1:0,y1:0,x2:0,y2:1,stop:0 #E4E4E4,stop:1 #E4E4E4);\n"
"}\n"
"\n"
"QWidget[nav=\"top\"] QAbstractButton:hover,QWidget[nav=\"top\"] QAbstractButton:pressed,QWidget[nav=\"top\"] QAbstractButton:checked{\n"
"border-style:solid;\n"
"border-width:0px 0px 2px 0px;\n"
"padding:4px 4px 2px 4px;\n"
"border-color:#00BB9E;\n"
"background:qlineargradient(spread:pad,x1:0,y1:0,x2:0,y2:1,stop:0 #F6F6F6,stop:1 #F6F6F6);\n"
"}\n"
"\n"
"QWidget[nav=\"left\"] QAbstractButton{\n"
"border-radius:0px;\n"
"color:#57595B;\n"
"background:none;\n"
"border-style:none;\n"
"}\n"
"\n"
"QWidget[nav=\"left\"] QAbstractButton:hover{\n"
"color:#FFFFFF;\n"
"background-color:#00BB9E;\n"
"}\n"
"\n"
"QWidget[nav=\"left\"] QAbstractButton:checked,QWidget[nav=\"left\"] QAbstractButton:pressed{\n"
"color:#57595B;\n"
"border-style:solid;\n"
"border-width:0px 0px 0px 2px;\n"
"padding:4px 4px 4px 2px;\n"
"border-color:#00BB9E;\n"
"background-color:#FFFFFF;\n"
"}\n"
"\n"
"QWidget[video=\"true\"] QLabel{\n"
"color:#57595B;\n"
"border:1px solid #B6B6B6;\n"
"background:qlineargradient(spread:pad,x1:0,y1:0,x2:0,y2:1,stop:0 #E4E4E4,stop:1 #E4E4E4);\n"
"}\n"
"\n"
"QWidget[video=\"true\"] QLabel:focus{\n"
"border:1px solid #00BB9E;\n"
"background:qlineargradient(spread:pad,x1:0,y1:0,x2:0,y2:1,stop:0 #F6F6F6,stop:1 #F6F6F6);\n"
"}\n"
"\n"
"QLineEdit,QTextEdit,QPlainTextEdit,QSpinBox,QDoubleSpinBox,QComboBox,QDateEdit,QTimeEdit,QDateTimeEdit{\n"
"border:1px solid #B6B6B6;\n"
"border-radius:3px;\n"
"padding:2px;\n"
"background:none;\n"
"selection-background-color:#00BB9E;\n"
"selection-color:#FFFFFF;\n"
"}\n"
"\n"
"QLineEdit:focus,QTextEdit:focus,QPlainTextEdit:focus,QSpinBox:focus,QDoubleSpinBox:focus,QComboBox:focus,QDateEdit:focus,QTimeEdit:focus,QDateTimeEdit:focus,QLineEdit:hover,QTextEdit:hover,QPlainTextEdit:hover,QSpinBox:hover,QDoubleSpinBox:hover,QComboBox:hover,QDateEdit:hover,QTimeEdit:hover,QDateTimeEdit:hover{\n"
"border:1px solid #B6B6B6;\n"
"}\n"
"\n"
"QLineEdit[echoMode=\"2\"]{\n"
"lineedit-password-character:9679;\n"
"}\n"
"\n"
".QFrame{\n"
"border:1px solid #B6B6B6;\n"
"border-radius:3px;\n"
"}\n"
"\n"
".QGroupBox{\n"
"border:1px solid #B6B6B6;\n"
"border-radius:5px;\n"
"margin-top:3ex;\n"
"}\n"
"\n"
".QGroupBox::title{\n"
"subcontrol-origin:margin;\n"
"position:relative;\n"
"left:10px;\n"
"}\n"
"\n"
".QPushButton,.QToolButton{\n"
"border-style:none;\n"
"border:1px solid #B6B6B6;\n"
"color:#57595B;\n"
"padding:5px;\n"
"min-height:15px;\n"
"border-radius:5px;\n"
"background:qlineargradient(spread:pad,x1:0,y1:0,x2:0,y2:1,stop:0 #E4E4E4,stop:1 #E4E4E4);\n"
"}\n"
"\n"
".QPushButton:hover,.QToolButton:hover{\n"
"background:qlineargradient(spread:pad,x1:0,y1:0,x2:0,y2:1,stop:0 #F6F6F6,stop:1 #F6F6F6);\n"
"}\n"
"\n"
".QPushButton:pressed,.QToolButton:pressed{\n"
"background:qlineargradient(spread:pad,x1:0,y1:0,x2:0,y2:1,stop:0 #E4E4E4,stop:1 #E4E4E4);\n"
"}\n"
"\n"
".QToolButton::menu-indicator{\n"
"image:None;\n"
"}\n"
"\n"
"QToolButton#btnMenu,QPushButton#btnMenu_Min,QPushButton#btnMenu_Max,QPushButton#btnMenu_Close{\n"
"border-radius:3px;\n"
"color:#57595B;\n"
"padding:3px;\n"
"margin:0px;\n"
"background:none;\n"
"border-style:none;\n"
"}\n"
"\n"
"QToolButton#btnMenu:hover,QPushButton#btnMenu_Min:hover,QPushButton#btnMenu_Max:hover{\n"
"color:#FFFFFF;\n"
"margin:1px 1px 2px 1px;\n"
"background-color:rgba(51,127,209,230);\n"
"}\n"
"\n"
"QPushButton#btnMenu_Close:hover{\n"
"color:#FFFFFF;\n"
"margin:1px 1px 2px 1px;\n"
"background-color:rgba(238,0,0,128);\n"
"}\n"
"\n"
"QRadioButton::indicator{\n"
"width:15px;\n"
"height:15px;\n"
"}\n"
"\n"
"QRadioButton::indicator::unchecked{\n"
"image:url(./flatwhite/icons/radiobutton_unchecked.png);\n"
"}\n"
"\n"
"QRadioButton::indicator::unchecked:disabled{\n"
"image:url(./flatwhite/icons/radiobutton_unchecked_disable.png);\n"
"}\n"
"\n"
"QRadioButton::indicator::checked{\n"
"image:url(./flatwhite/icons/radiobutton_checked.png);\n"
"}\n"
"\n"
"QRadioButton::indicator::checked:disabled{\n"
"image:url(./flatwhite/icons/radiobutton_checked_disable.png);\n"
"}\n"
"\n"
"QGroupBox::indicator,QTreeWidget::indicator,QListWidget::indicator{\n"
"padding:0px -3px 0px 0px;\n"
"}\n"
"\n"
"QCheckBox::indicator,QGroupBox::indicator,QTreeWidget::indicator,QListWidget::indicator{\n"
"width:13px;\n"
"height:13px;\n"
"}\n"
"\n"
"QCheckBox::indicator:unchecked,QGroupBox::indicator:unchecked,QTreeWidget::indicator:unchecked,QListWidget::indicator:unchecked{\n"
"image:url(./flatwhite/icons/checkbox_unchecked.png);\n"
"}\n"
"\n"
"QCheckBox::indicator:unchecked:disabled,QGroupBox::indicator:unchecked:disabled,QTreeWidget::indicator:unchecked:disabled,QListWidget::indicator:disabled{\n"
"image:url(./flatwhite/icons/checkbox_unchecked_disable.png);\n"
"}\n"
"\n"
"QCheckBox::indicator:checked,QGroupBox::indicator:checked,QTreeWidget::indicator:checked,QListWidget::indicator:checked{\n"
"image:url(./flatwhite/icons/checkbox_checked.png);\n"
"}\n"
"\n"
"QCheckBox::indicator:checked:disabled,QGroupBox::indicator:checked:disabled,QTreeWidget::indicator:checked:disabled,QListWidget::indicator:checked:disabled{\n"
"image:url(./flatwhite/icons/checkbox_checked_disable.png);\n"
"}\n"
"\n"
"QCheckBox::indicator:indeterminate,QGroupBox::indicator:indeterminate,QTreeWidget::indicator:indeterminate,QListWidget::indicator:indeterminate{\n"
"image:url(./flatwhite/icons/checkbox_parcial.png);\n"
"}\n"
"\n"
"QCheckBox::indicator:indeterminate:disabled,QGroupBox::indicator:indeterminate:disabled,QTreeWidget::indicator:indeterminate:disabled,QListWidget::indicator:indeterminate:disabled{\n"
"image:url(./flatwhite/icons/checkbox_parcial_disable.png);\n"
"}\n"
"\n"
"QTimeEdit::up-button,QDateEdit::up-button,QDateTimeEdit::up-button,QDoubleSpinBox::up-button,QSpinBox::up-button{\n"
"image:url(./flatwhite/icons/add_top.png);\n"
"width:10px;\n"
"height:10px;\n"
"padding:2px 5px 0px 0px;\n"
"}\n"
"\n"
"QTimeEdit::down-button,QDateEdit::down-button,QDateTimeEdit::down-button,QDoubleSpinBox::down-button,QSpinBox::down-button{\n"
"image:url(./flatwhite/icons/add_bottom.png);\n"
"width:10px;\n"
"height:10px;\n"
"padding:0px 5px 2px 0px;\n"
"}\n"
"\n"
"QTimeEdit::up-button:pressed,QDateEdit::up-button:pressed,QDateTimeEdit::up-button:pressed,QDoubleSpinBox::up-button:pressed,QSpinBox::up-button:pressed{\n"
"top:-2px;\n"
"}\n"
"\n"
"QTimeEdit::down-button:pressed,QDateEdit::down-button:pressed,QDateTimeEdit::down-button:pressed,QDoubleSpinBox::down-button:pressed,QSpinBox::down-button:pressed,QSpinBox::down-button:pressed{\n"
"bottom:-2px;\n"
"}\n"
"\n"
"QComboBox::down-arrow,QDateEdit[calendarPopup=\"true\"]::down-arrow,QTimeEdit[calendarPopup=\"true\"]::down-arrow,QDateTimeEdit[calendarPopup=\"true\"]::down-arrow{\n"
"image:url(./flatwhite/icons/add_bottom.png);\n"
"width:10px;\n"
"height:10px;\n"
"right:2px;\n"
"}\n"
"\n"
"QComboBox::drop-down,QDateEdit::drop-down,QTimeEdit::drop-down,QDateTimeEdit::drop-down{\n"
"subcontrol-origin:padding;\n"
"subcontrol-position:top right;\n"
"width:15px;\n"
"border-left-width:0px;\n"
"border-left-style:solid;\n"
"border-top-right-radius:3px;\n"
"border-bottom-right-radius:3px;\n"
"border-left-color:#B6B6B6;\n"
"}\n"
"\n"
"QComboBox::drop-down:on{\n"
"top:1px;\n"
"}\n"
"\n"
"QMenuBar::item{\n"
"color:#57595B;\n"
"background-color:#E4E4E4;\n"
"margin:0px;\n"
"padding:3px 10px;\n"
"}\n"
"\n"
"QMenu,QMenuBar,QMenu:disabled,QMenuBar:disabled{\n"
"color:#57595B;\n"
"background-color:#E4E4E4;\n"
"border:1px solid #B6B6B6;\n"
"margin:0px;\n"
"}\n"
"\n"
"QMenu::item{\n"
"padding:3px 20px;\n"
"}\n"
"\n"
"QMenu::indicator{\n"
"width:13px;\n"
"height:13px;\n"
"}\n"
"\n"
"QMenu::item:selected,QMenuBar::item:selected{\n"
"color:#57595B;\n"
"border:0px solid #B6B6B6;\n"
"background:#F6F6F6;\n"
"}\n"
"\n"
"QMenu::separator{\n"
"height:1px;\n"
"background:#B6B6B6;\n"
"}\n"
"\n"
"QProgressBar{\n"
"min-height:10px;\n"
"background:#E4E4E4;\n"
"border-radius:5px;\n"
"text-align:center;\n"
"border:1px solid #E4E4E4;\n"
"}\n"
"\n"
"QProgressBar:chunk{\n"
"border-radius:5px;\n"
"background-color:#B6B6B6;\n"
"}\n"
"\n"
"QSlider::groove:horizontal{\n"
"background:#E4E4E4;\n"
"height:8px;\n"
"border-radius:4px;\n"
"}\n"
"\n"
"QSlider::add-page:horizontal{\n"
"background:#E4E4E4;\n"
"height:8px;\n"
"border-radius:4px;\n"
"}\n"
"\n"
"QSlider::sub-page:horizontal{\n"
"background:#B6B6B6;\n"
"height:8px;\n"
"border-radius:4px;\n"
"}\n"
"\n"
"QSlider::handle:horizontal{\n"
"width:13px;\n"
"margin-top:-3px;\n"
"margin-bottom:-3px;\n"
"border-radius:6px;\n"
"background:qradialgradient(spread:pad,cx:0.5,cy:0.5,radius:0.5,fx:0.5,fy:0.5,stop:0.6 #FFFFFF,stop:0.8 #B6B6B6);\n"
"}\n"
"\n"
"QSlider::groove:vertical{\n"
"width:8px;\n"
"border-radius:4px;\n"
"background:#E4E4E4;\n"
"}\n"
"\n"
"QSlider::add-page:vertical{\n"
"width:8px;\n"
"border-radius:4px;\n"
"background:#E4E4E4;\n"
"}\n"
"\n"
"QSlider::sub-page:vertical{\n"
"width:8px;\n"
"border-radius:4px;\n"
"background:#B6B6B6;\n"
"}\n"
"\n"
"QSlider::handle:vertical{\n"
"height:14px;\n"
"margin-left:-3px;\n"
"margin-right:-3px;\n"
"border-radius:6px;\n"
"background:qradialgradient(spread:pad,cx:0.5,cy:0.5,radius:0.5,fx:0.5,fy:0.5,stop:0.6 #FFFFFF,stop:0.8 #B6B6B6);\n"
"}\n"
"\n"
"QScrollBar:horizontal{\n"
"background:#E4E4E4;\n"
"padding:0px;\n"
"border-radius:6px;\n"
"max-height:12px;\n"
"}\n"
"\n"
"QScrollBar::handle:horizontal{\n"
"background:#B6B6B6;\n"
"min-width:50px;\n"
"border-radius:6px;\n"
"}\n"
"\n"
"QScrollBar::handle:horizontal:hover{\n"
"background:#00BB9E;\n"
"}\n"
"\n"
"QScrollBar::handle:horizontal:pressed{\n"
"background:#00BB9E;\n"
"}\n"
"\n"
"QScrollBar::add-page:horizontal{\n"
"background:none;\n"
"}\n"
"\n"
"QScrollBar::sub-page:horizontal{\n"
"background:none;\n"
"}\n"
"\n"
"QScrollBar::add-line:horizontal{\n"
"background:none;\n"
"}\n"
"\n"
"QScrollBar::sub-line:horizontal{\n"
"background:none;\n"
"}\n"
"\n"
"QScrollBar:vertical{\n"
"background:#E4E4E4;\n"
"padding:0px;\n"
"border-radius:6px;\n"
"max-width:12px;\n"
"}\n"
"\n"
"QScrollBar::handle:vertical{\n"
"background:#B6B6B6;\n"
"min-height:50px;\n"
"border-radius:6px;\n"
"}\n"
"\n"
"QScrollBar::handle:vertical:hover{\n"
"background:#00BB9E;\n"
"}\n"
"\n"
"QScrollBar::handle:vertical:pressed{\n"
"background:#00BB9E;\n"
"}\n"
"\n"
"QScrollBar::add-page:vertical{\n"
"background:none;\n"
"}\n"
"\n"
"QScrollBar::sub-page:vertical{\n"
"background:none;\n"
"}\n"
"\n"
"QScrollBar::add-line:vertical{\n"
"background:none;\n"
"}\n"
"\n"
"QScrollBar::sub-line:vertical{\n"
"background:none;\n"
"}\n"
"\n"
"QScrollArea{\n"
"border:0px;\n"
"}\n"
"\n"
"QTreeView,QListView,QTableView,QTabWidget::pane{\n"
"border:1px solid #B6B6B6;\n"
"selection-background-color:#F6F6F6;\n"
"selection-color:#57595B;\n"
"alternate-background-color:#F6F6F6;\n"
"gridline-color:#B6B6B6;\n"
"}\n"
"\n"
"QTreeView::branch:closed:has-children{\n"
"margin:4px;\n"
"border-image:url(./flatwhite/icons/branch_open.png);\n"
"}\n"
"\n"
"QTreeView::branch:open:has-children{\n"
"margin:4px;\n"
"border-image:url(./flatwhite/icons/branch_close.png);\n"
"}\n"
"\n"
"QTreeView,QListView,QTableView,QSplitter::handle,QTreeView::branch{\n"
"background:#FFFFFF;\n"
"}\n"
"\n"
"QTableView::item:selected,QListView::item:selected,QTreeView::item:selected{\n"
"color:#57595B;\n"
"background:qlineargradient(spread:pad,x1:0,y1:0,x2:0,y2:1,stop:0 #E4E4E4,stop:1 #E4E4E4);\n"
"}\n"
"\n"
"QTableView::item:hover,QListView::item:hover,QTreeView::item:hover,QHeaderView{\n"
"color:#57595B;\n"
"background:qlineargradient(spread:pad,x1:0,y1:0,x2:0,y2:1,stop:0 #F6F6F6,stop:1 #F6F6F6);\n"
"}\n"
"\n"
"QTableView::item,QListView::item,QTreeView::item{\n"
"padding:1px;\n"
"margin:0px;\n"
"}\n"
"\n"
"QHeaderView::section,QTableCornerButton:section{\n"
"padding:3px;\n"
"margin:0px;\n"
"color:#57595B;\n"
"border:1px solid #B6B6B6;\n"
"border-left-width:0px;\n"
"border-right-width:1px;\n"
"border-top-width:0px;\n"
"border-bottom-width:1px;\n"
"background:qlineargradient(spread:pad,x1:0,y1:0,x2:0,y2:1,stop:0 #F6F6F6,stop:1 #F6F6F6);\n"
"}\n"
"\n"
"QTabBar::tab{\n"
"border:1px solid #B6B6B6;\n"
"color:#57595B;\n"
"margin:0px;\n"
"background:qlineargradient(spread:pad,x1:0,y1:0,x2:0,y2:1,stop:0 #F6F6F6,stop:1 #F6F6F6);\n"
"}\n"
"\n"
"QTabBar::tab:selected,QTabBar::tab:hover{\n"
"border-style:solid;\n"
"border-color:#00BB9E;\n"
"background:#FFFFFF;\n"
"}\n"
"\n"
"QTabBar::tab:top,QTabBar::tab:bottom{\n"
"padding:3px 8px 3px 8px;\n"
"}\n"
"\n"
"QTabBar::tab:left,QTabBar::tab:right{\n"
"padding:8px 3px 8px 3px;\n"
"}\n"
"\n"
"QTabBar::tab:top:selected,QTabBar::tab:top:hover{\n"
"border-width:2px 0px 0px 0px;\n"
"}\n"
"\n"
"QTabBar::tab:right:selected,QTabBar::tab:right:hover{\n"
"border-width:0px 0px 0px 2px;\n"
"}\n"
"\n"
"QTabBar::tab:bottom:selected,QTabBar::tab:bottom:hover{\n"
"border-width:0px 0px 2px 0px;\n"
"}\n"
"\n"
"QTabBar::tab:left:selected,QTabBar::tab:left:hover{\n"
"border-width:0px 2px 0px 0px;\n"
"}\n"
"\n"
"QTabBar::tab:first:top:selected,QTabBar::tab:first:top:hover,QTabBar::tab:first:bottom:selected,QTabBar::tab:first:bottom:hover{\n"
"border-left-width:1px;\n"
"border-left-color:#B6B6B6;\n"
"}\n"
"\n"
"QTabBar::tab:first:left:selected,QTabBar::tab:first:left:hover,QTabBar::tab:first:right:selected,QTabBar::tab:first:right:hover{\n"
"border-top-width:1px;\n"
"border-top-color:#B6B6B6;\n"
"}\n"
"\n"
"QTabBar::tab:last:top:selected,QTabBar::tab:last:top:hover,QTabBar::tab:last:bottom:selected,QTabBar::tab:last:bottom:hover{\n"
"border-right-width:1px;\n"
"border-right-color:#B6B6B6;\n"
"}\n"
"\n"
"QTabBar::tab:last:left:selected,QTabBar::tab:last:left:hover,QTabBar::tab:last:right:selected,QTabBar::tab:last:right:hover{\n"
"border-bottom-width:1px;\n"
"border-bottom-color:#B6B6B6;\n"
"}\n"
"\n"
"QStatusBar::item{\n"
"border:0px solid #E4E4E4;\n"
"border-radius:3px;\n"
"}\n"
"\n"
"QToolBox::tab,QGroupBox#gboxDevicePanel,QGroupBox#gboxDeviceTitle,QFrame#gboxDevicePanel,QFrame#gboxDeviceTitle{\n"
"padding:3px;\n"
"border-radius:5px;\n"
"color:#57595B;\n"
"background:qlineargradient(spread:pad,x1:0,y1:0,x2:0,y2:1,stop:0 #E4E4E4,stop:1 #E4E4E4);\n"
"}\n"
"\n"
"QToolTip{\n"
"border:0px solid #57595B;\n"
"padding:1px;\n"
"color:#57595B;\n"
"background:qlineargradient(spread:pad,x1:0,y1:0,x2:0,y2:1,stop:0 #E4E4E4,stop:1 #E4E4E4);\n"
"}\n"
"\n"
"QToolBox::tab:selected{\n"
"background:qlineargradient(spread:pad,x1:0,y1:0,x2:0,y2:1,stop:0 #F6F6F6,stop:1 #F6F6F6);\n"
"}\n"
"\n"
"QPrintPreviewDialog QToolButton{\n"
"border:0px solid #57595B;\n"
"border-radius:0px;\n"
"margin:0px;\n"
"padding:3px;\n"
"background:none;\n"
"}\n"
"\n"
"QColorDialog QPushButton,QFileDialog QPushButton{\n"
"min-width:80px;\n"
"}\n"
"\n"
"QToolButton#qt_calendar_prevmonth{\n"
"icon-size:0px;\n"
"min-width:20px;\n"
"image:url(./flatwhite/icons/calendar_prevmonth.png);\n"
"}\n"
"\n"
"QToolButton#qt_calendar_nextmonth{\n"
"icon-size:0px;\n"
"min-width:20px;\n"
"image:url(./flatwhite/icons/calendar_nextmonth.png);\n"
"}\n"
"\n"
"QToolButton#qt_calendar_prevmonth,QToolButton#qt_calendar_nextmonth,QToolButton#qt_calendar_monthbutton,QToolButton#qt_calendar_yearbutton{\n"
"border:0px solid #57595B;\n"
"border-radius:3px;\n"
"margin:3px 3px 3px 3px;\n"
"padding:3px;\n"
"background:none;\n"
"}\n"
"\n"
"QToolButton#qt_calendar_prevmonth:hover,QToolButton#qt_calendar_nextmonth:hover,QToolButton#qt_calendar_monthbutton:hover,QToolButton#qt_calendar_yearbutton:hover,QToolButton#qt_calendar_prevmonth:pressed,QToolButton#qt_calendar_nextmonth:pressed,QToolButton#qt_calendar_monthbutton:pressed,QToolButton#qt_calendar_yearbutton:pressed{\n"
"border:1px solid #B6B6B6;\n"
"}\n"
"\n"
"QCalendarWidget QSpinBox#qt_calendar_yearedit{\n"
"margin:2px;\n"
"}\n"
"\n"
"QCalendarWidget QToolButton::menu-indicator{\n"
"image:None;\n"
"}\n"
"\n"
"QCalendarWidget QTableView{\n"
"border-width:0px;\n"
"}\n"
"\n"
"QCalendarWidget QWidget#qt_calendar_navigationbar{\n"
"border:1px solid #B6B6B6;\n"
"border-width:1px 1px 0px 1px;\n"
"background:qlineargradient(spread:pad,x1:0,y1:0,x2:0,y2:1,stop:0 #E4E4E4,stop:1 #E4E4E4);\n"
"}\n"
"\n"
"QComboBox QAbstractItemView::item{\n"
"min-height:20px;\n"
"min-width:10px;\n"
"}\n"
"\n"
"QTableView[model=\"true\"]::item{\n"
"padding:0px;\n"
"margin:0px;\n"
"}\n"
"\n"
"QTableView QLineEdit,QTableView QComboBox,QTableView QSpinBox,QTableView QDoubleSpinBox,QTableView QDateEdit,QTableView QTimeEdit,QTableView QDateTimeEdit{\n"
"border-width:0px;\n"
"border-radius:0px;\n"
"}\n"
"\n"
"QTableView QLineEdit:focus,QTableView QComboBox:focus,QTableView QSpinBox:focus,QTableView QDoubleSpinBox:focus,QTableView QDateEdit:focus,QTableView QTimeEdit:focus,QTableView QDateTimeEdit:focus{\n"
"border-width:0px;\n"
"border-radius:0px;\n"
"}\n"
"\n"
"QLineEdit,QTextEdit,QPlainTextEdit,QSpinBox,QDoubleSpinBox,QComboBox,QDateEdit,QTimeEdit,QDateTimeEdit{\n"
"background:#FFFFFF;\n"
"}\n"
"\n"
"QTabWidget::pane:top{top:-1px;}\n"
"QTabWidget::pane:bottom{bottom:-1px;}\n"
"QTabWidget::pane:left{right:-1px;}\n"
"QTabWidget::pane:right{left:-1px;}\n"
"\n"
"*:disabled{\n"
"background:#FFFFFF;\n"
"border-color:#E4E4E4;\n"
"color:#B6B6B6;\n"
"}\n"
"\n"
"/*TextColor:#57595B*/\n"
"/*PanelColor:#FFFFFF*/\n"
"/*BorderColor:#B6B6B6*/\n"
"/*NormalColorStart:#E4E4E4*/\n"
"/*NormalColorEnd:#E4E4E4*/\n"
"/*DarkColorStart:#F6F6F6*/\n"
"/*DarkColorEnd:#F6F6F6*/\n"
"/*HighColor:#00BB9E*/")
        MainWindow.setDocumentMode(False)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.toolBox = QtWidgets.QToolBox(self.centralwidget)
        self.toolBox.setGeometry(QtCore.QRect(1000, 60, 331, 721))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(13)
        self.toolBox.setFont(font)
        self.toolBox.setStyleSheet("QWidget{\n"
"boder-radius: 5px;\n"
"}")
        self.toolBox.setObjectName("toolBox")
        self.NosieFilter = QtWidgets.QWidget()
        self.NosieFilter.setGeometry(QtCore.QRect(0, 0, 331, 541))
        self.NosieFilter.setObjectName("NosieFilter")
        self.layoutWidget = QtWidgets.QWidget(self.NosieFilter)
        self.layoutWidget.setGeometry(QtCore.QRect(10, 0, 311, 55))
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label_2 = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(11)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_3.addWidget(self.label_2)
        self.GSsigmaSlider = QtWidgets.QSlider(self.layoutWidget)
        self.GSsigmaSlider.setMinimum(0)
        self.GSsigmaSlider.setMaximum(100)
        self.GSsigmaSlider.setOrientation(QtCore.Qt.Horizontal)
        self.GSsigmaSlider.setTickPosition(QtWidgets.QSlider.NoTicks)
        self.GSsigmaSlider.setObjectName("GSsigmaSlider")
        self.verticalLayout_3.addWidget(self.GSsigmaSlider)
        self.layoutWidget_2 = QtWidgets.QWidget(self.NosieFilter)
        self.layoutWidget_2.setGeometry(QtCore.QRect(10, 150, 311, 55))
        self.layoutWidget_2.setObjectName("layoutWidget_2")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.layoutWidget_2)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.label_3 = QtWidgets.QLabel(self.layoutWidget_2)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(11)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.verticalLayout_4.addWidget(self.label_3)
        self.UniSigmaSlider = QtWidgets.QSlider(self.layoutWidget_2)
        self.UniSigmaSlider.setMinimum(0)
        self.UniSigmaSlider.setMaximum(100)
        self.UniSigmaSlider.setOrientation(QtCore.Qt.Horizontal)
        self.UniSigmaSlider.setTickPosition(QtWidgets.QSlider.NoTicks)
        self.UniSigmaSlider.setObjectName("UniSigmaSlider")
        self.verticalLayout_4.addWidget(self.UniSigmaSlider)
        self.layoutWidget_3 = QtWidgets.QWidget(self.NosieFilter)
        self.layoutWidget_3.setGeometry(QtCore.QRect(10, 260, 311, 41))
        self.layoutWidget_3.setObjectName("layoutWidget_3")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.layoutWidget_3)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_11 = QtWidgets.QLabel(self.layoutWidget_3)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(11)
        self.label_11.setFont(font)
        self.label_11.setObjectName("label_11")
        self.horizontalLayout_2.addWidget(self.label_11)
        self.GammaSlider = QtWidgets.QSlider(self.layoutWidget_3)
        self.GammaSlider.setMinimum(0)
        self.GammaSlider.setMaximum(100)
        self.GammaSlider.setOrientation(QtCore.Qt.Horizontal)
        self.GammaSlider.setTickPosition(QtWidgets.QSlider.NoTicks)
        self.GammaSlider.setObjectName("GammaSlider")
        self.horizontalLayout_2.addWidget(self.GammaSlider)
        self.layoutWidget_4 = QtWidgets.QWidget(self.NosieFilter)
        self.layoutWidget_4.setGeometry(QtCore.QRect(10, 310, 311, 41))
        self.layoutWidget_4.setObjectName("layoutWidget_4")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.layoutWidget_4)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_12 = QtWidgets.QLabel(self.layoutWidget_4)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(11)
        self.label_12.setFont(font)
        self.label_12.setObjectName("label_12")
        self.horizontalLayout_3.addWidget(self.label_12)
        self.ExpSlider = QtWidgets.QSlider(self.layoutWidget_4)
        self.ExpSlider.setMinimum(0)
        self.ExpSlider.setMaximum(100)
        self.ExpSlider.setOrientation(QtCore.Qt.Horizontal)
        self.ExpSlider.setTickPosition(QtWidgets.QSlider.NoTicks)
        self.ExpSlider.setObjectName("ExpSlider")
        self.horizontalLayout_3.addWidget(self.ExpSlider)
        self.layoutWidget_5 = QtWidgets.QWidget(self.NosieFilter)
        self.layoutWidget_5.setGeometry(QtCore.QRect(170, 360, 151, 31))
        self.layoutWidget_5.setObjectName("layoutWidget_5")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.layoutWidget_5)
        self.horizontalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label_14 = QtWidgets.QLabel(self.layoutWidget_5)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(11)
        self.label_14.setFont(font)
        self.label_14.setObjectName("label_14")
        self.horizontalLayout_5.addWidget(self.label_14)
        self.MedianspinBox = QtWidgets.QSpinBox(self.layoutWidget_5)
        self.MedianspinBox.setMinimum(1)
        self.MedianspinBox.setSingleStep(2)
        self.MedianspinBox.setProperty("value", 1)
        self.MedianspinBox.setObjectName("MedianspinBox")
        self.horizontalLayout_5.addWidget(self.MedianspinBox)
        self.layoutWidget1 = QtWidgets.QWidget(self.NosieFilter)
        self.layoutWidget1.setGeometry(QtCore.QRect(10, 60, 311, 84))
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.layoutWidget1)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label = QtWidgets.QLabel(self.layoutWidget1)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(11)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.verticalLayout_2.addWidget(self.label)
        self.SaltSlider = QtWidgets.QSlider(self.layoutWidget1)
        self.SaltSlider.setMaximum(100)
        self.SaltSlider.setProperty("value", 0)
        self.SaltSlider.setSliderPosition(0)
        self.SaltSlider.setOrientation(QtCore.Qt.Horizontal)
        self.SaltSlider.setObjectName("SaltSlider")
        self.verticalLayout_2.addWidget(self.SaltSlider)
        self.PepperSlider = QtWidgets.QSlider(self.layoutWidget1)
        self.PepperSlider.setMaximum(100)
        self.PepperSlider.setOrientation(QtCore.Qt.Horizontal)
        self.PepperSlider.setTickPosition(QtWidgets.QSlider.NoTicks)
        self.PepperSlider.setObjectName("PepperSlider")
        self.verticalLayout_2.addWidget(self.PepperSlider)
        self.layoutWidget2 = QtWidgets.QWidget(self.NosieFilter)
        self.layoutWidget2.setGeometry(QtCore.QRect(11, 210, 311, 41))
        self.layoutWidget2.setObjectName("layoutWidget2")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.layoutWidget2)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_6 = QtWidgets.QLabel(self.layoutWidget2)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(11)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.horizontalLayout.addWidget(self.label_6)
        self.ReilSlider = QtWidgets.QSlider(self.layoutWidget2)
        self.ReilSlider.setMinimum(0)
        self.ReilSlider.setMaximum(100)
        self.ReilSlider.setOrientation(QtCore.Qt.Horizontal)
        self.ReilSlider.setTickPosition(QtWidgets.QSlider.NoTicks)
        self.ReilSlider.setObjectName("ReilSlider")
        self.horizontalLayout.addWidget(self.ReilSlider)
        self.layoutWidget3 = QtWidgets.QWidget(self.NosieFilter)
        self.layoutWidget3.setGeometry(QtCore.QRect(10, 360, 151, 31))
        self.layoutWidget3.setObjectName("layoutWidget3")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.layoutWidget3)
        self.horizontalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_13 = QtWidgets.QLabel(self.layoutWidget3)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(11)
        self.label_13.setFont(font)
        self.label_13.setObjectName("label_13")
        self.horizontalLayout_4.addWidget(self.label_13)
        self.MeanspinBox = QtWidgets.QSpinBox(self.layoutWidget3)
        self.MeanspinBox.setMinimum(1)
        self.MeanspinBox.setSingleStep(2)
        self.MeanspinBox.setProperty("value", 1)
        self.MeanspinBox.setObjectName("MeanspinBox")
        self.horizontalLayout_4.addWidget(self.MeanspinBox)
        self.layoutWidget4 = QtWidgets.QWidget(self.NosieFilter)
        self.layoutWidget4.setGeometry(QtCore.QRect(10, 400, 311, 31))
        self.layoutWidget4.setObjectName("layoutWidget4")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.layoutWidget4)
        self.horizontalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.label_15 = QtWidgets.QLabel(self.layoutWidget4)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(11)
        self.label_15.setFont(font)
        self.label_15.setObjectName("label_15")
        self.horizontalLayout_6.addWidget(self.label_15)
        self.BilaspinBox = QtWidgets.QSpinBox(self.layoutWidget4)
        self.BilaspinBox.setMinimum(1)
        self.BilaspinBox.setSingleStep(2)
        self.BilaspinBox.setProperty("value", 1)
        self.BilaspinBox.setObjectName("BilaspinBox")
        self.horizontalLayout_6.addWidget(self.BilaspinBox)
        self.BilaCspinBox = QtWidgets.QSpinBox(self.layoutWidget4)
        self.BilaCspinBox.setMinimum(1)
        self.BilaCspinBox.setSingleStep(2)
        self.BilaCspinBox.setProperty("value", 1)
        self.BilaCspinBox.setObjectName("BilaCspinBox")
        self.horizontalLayout_6.addWidget(self.BilaCspinBox)
        self.BilaSspinBox = QtWidgets.QSpinBox(self.layoutWidget4)
        self.BilaSspinBox.setMinimum(1)
        self.BilaSspinBox.setSingleStep(2)
        self.BilaSspinBox.setProperty("value", 1)
        self.BilaSspinBox.setObjectName("BilaSspinBox")
        self.horizontalLayout_6.addWidget(self.BilaSspinBox)
        self.layoutWidget5 = QtWidgets.QWidget(self.NosieFilter)
        self.layoutWidget5.setGeometry(QtCore.QRect(10, 440, 311, 31))
        self.layoutWidget5.setObjectName("layoutWidget5")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout(self.layoutWidget5)
        self.horizontalLayout_7.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.label_16 = QtWidgets.QLabel(self.layoutWidget5)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(11)
        self.label_16.setFont(font)
        self.label_16.setObjectName("label_16")
        self.horizontalLayout_7.addWidget(self.label_16)
        self.GausspinBox = QtWidgets.QSpinBox(self.layoutWidget5)
        self.GausspinBox.setMinimum(1)
        self.GausspinBox.setSingleStep(2)
        self.GausspinBox.setProperty("value", 1)
        self.GausspinBox.setObjectName("GausspinBox")
        self.horizontalLayout_7.addWidget(self.GausspinBox)
        self.GaussigmaSlider = QtWidgets.QSlider(self.layoutWidget5)
        self.GaussigmaSlider.setMinimum(-100)
        self.GaussigmaSlider.setMaximum(100)
        self.GaussigmaSlider.setOrientation(QtCore.Qt.Horizontal)
        self.GaussigmaSlider.setTickPosition(QtWidgets.QSlider.NoTicks)
        self.GaussigmaSlider.setObjectName("GaussigmaSlider")
        self.horizontalLayout_7.addWidget(self.GaussigmaSlider)
        self.toolBox.addItem(self.NosieFilter, "")
        self.GeoTrans = QtWidgets.QWidget()
        self.GeoTrans.setGeometry(QtCore.QRect(0, 0, 331, 541))
        self.GeoTrans.setObjectName("GeoTrans")
        self.pushButtonLeft = QtWidgets.QPushButton(self.GeoTrans)
        self.pushButtonLeft.setGeometry(QtCore.QRect(260, 0, 61, 61))
        self.pushButtonLeft.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/ok/icons/right.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButtonLeft.setIcon(icon)
        self.pushButtonLeft.setIconSize(QtCore.QSize(50, 50))
        self.pushButtonLeft.setObjectName("pushButtonLeft")
        self.pushButtonRight = QtWidgets.QPushButton(self.GeoTrans)
        self.pushButtonRight.setGeometry(QtCore.QRect(170, 0, 61, 61))
        self.pushButtonRight.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/ok/icons/left.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButtonRight.setIcon(icon1)
        self.pushButtonRight.setIconSize(QtCore.QSize(50, 50))
        self.pushButtonRight.setObjectName("pushButtonRight")
        self.layoutWidget6 = QtWidgets.QWidget(self.GeoTrans)
        self.layoutWidget6.setGeometry(QtCore.QRect(10, 0, 151, 61))
        self.layoutWidget6.setObjectName("layoutWidget6")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout(self.layoutWidget6)
        self.horizontalLayout_8.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout()
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.label_17 = QtWidgets.QLabel(self.layoutWidget6)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(11)
        self.label_17.setFont(font)
        self.label_17.setObjectName("label_17")
        self.verticalLayout_7.addWidget(self.label_17)
        self.anglelabe = QtWidgets.QLabel(self.layoutWidget6)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(11)
        self.anglelabe.setFont(font)
        self.anglelabe.setText("")
        self.anglelabe.setObjectName("anglelabe")
        self.verticalLayout_7.addWidget(self.anglelabe)
        self.horizontalLayout_8.addLayout(self.verticalLayout_7)
        self.Rotatedial = QtWidgets.QDial(self.layoutWidget6)
        self.Rotatedial.setMaximum(359)
        self.Rotatedial.setObjectName("Rotatedial")
        self.horizontalLayout_8.addWidget(self.Rotatedial)
        self.widget = QtWidgets.QWidget(self.GeoTrans)
        self.widget.setGeometry(QtCore.QRect(20, 90, 291, 181))
        self.widget.setObjectName("widget")
        self.gridLayout = QtWidgets.QGridLayout(self.widget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.pushButtonCut = QtWidgets.QPushButton(self.widget)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(11)
        self.pushButtonCut.setFont(font)
        self.pushButtonCut.setObjectName("pushButtonCut")
        self.gridLayout.addWidget(self.pushButtonCut, 0, 0, 1, 1)
        self.pushButtonFrame = QtWidgets.QPushButton(self.widget)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(11)
        self.pushButtonFrame.setFont(font)
        self.pushButtonFrame.setObjectName("pushButtonFrame")
        self.gridLayout.addWidget(self.pushButtonFrame, 0, 1, 1, 1)
        self.pushButtonUpDown = QtWidgets.QPushButton(self.widget)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(11)
        self.pushButtonUpDown.setFont(font)
        self.pushButtonUpDown.setObjectName("pushButtonUpDown")
        self.gridLayout.addWidget(self.pushButtonUpDown, 1, 0, 1, 1)
        self.pushButtonHmerge = QtWidgets.QPushButton(self.widget)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(11)
        self.pushButtonHmerge.setFont(font)
        self.pushButtonHmerge.setObjectName("pushButtonHmerge")
        self.gridLayout.addWidget(self.pushButtonHmerge, 1, 1, 1, 1)
        self.pushButtonLeftRight = QtWidgets.QPushButton(self.widget)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(11)
        self.pushButtonLeftRight.setFont(font)
        self.pushButtonLeftRight.setObjectName("pushButtonLeftRight")
        self.gridLayout.addWidget(self.pushButtonLeftRight, 2, 0, 1, 1)
        self.pushButtonVmerge = QtWidgets.QPushButton(self.widget)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(11)
        self.pushButtonVmerge.setFont(font)
        self.pushButtonVmerge.setObjectName("pushButtonVmerge")
        self.gridLayout.addWidget(self.pushButtonVmerge, 2, 1, 1, 1)
        self.widget1 = QtWidgets.QWidget(self.GeoTrans)
        self.widget1.setGeometry(QtCore.QRect(7, 280, 311, 38))
        self.widget1.setObjectName("widget1")
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout(self.widget1)
        self.horizontalLayout_10.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.label_26 = QtWidgets.QLabel(self.widget1)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(11)
        self.label_26.setFont(font)
        self.label_26.setObjectName("label_26")
        self.horizontalLayout_12.addWidget(self.label_26)
        self.rowspinBox = QtWidgets.QSpinBox(self.widget1)
        self.rowspinBox.setObjectName("rowspinBox")
        self.horizontalLayout_12.addWidget(self.rowspinBox)
        self.label_27 = QtWidgets.QLabel(self.widget1)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(11)
        self.label_27.setFont(font)
        self.label_27.setObjectName("label_27")
        self.horizontalLayout_12.addWidget(self.label_27)
        self.colspinBox = QtWidgets.QSpinBox(self.widget1)
        self.colspinBox.setObjectName("colspinBox")
        self.horizontalLayout_12.addWidget(self.colspinBox)
        self.horizontalLayout_10.addLayout(self.horizontalLayout_12)
        self.pushButton4Merge = QtWidgets.QPushButton(self.widget1)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(11)
        self.pushButton4Merge.setFont(font)
        self.pushButton4Merge.setObjectName("pushButton4Merge")
        self.horizontalLayout_10.addWidget(self.pushButton4Merge)
        self.toolBox.addItem(self.GeoTrans, "")
        self.Enhancement = QtWidgets.QWidget()
        self.Enhancement.setGeometry(QtCore.QRect(0, 0, 331, 541))
        self.Enhancement.setObjectName("Enhancement")
        self.layoutWidget_6 = QtWidgets.QWidget(self.Enhancement)
        self.layoutWidget_6.setGeometry(QtCore.QRect(10, 0, 311, 55))
        self.layoutWidget_6.setObjectName("layoutWidget_6")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.layoutWidget_6)
        self.verticalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.label_4 = QtWidgets.QLabel(self.layoutWidget_6)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(11)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.verticalLayout_6.addWidget(self.label_4)
        self.BrightnessSlider = QtWidgets.QSlider(self.layoutWidget_6)
        self.BrightnessSlider.setMinimum(0)
        self.BrightnessSlider.setMaximum(200)
        self.BrightnessSlider.setProperty("value", 100)
        self.BrightnessSlider.setOrientation(QtCore.Qt.Horizontal)
        self.BrightnessSlider.setTickPosition(QtWidgets.QSlider.NoTicks)
        self.BrightnessSlider.setObjectName("BrightnessSlider")
        self.verticalLayout_6.addWidget(self.BrightnessSlider)
        self.layoutWidget_7 = QtWidgets.QWidget(self.Enhancement)
        self.layoutWidget_7.setGeometry(QtCore.QRect(10, 60, 311, 55))
        self.layoutWidget_7.setObjectName("layoutWidget_7")
        self.verticalLayout_13 = QtWidgets.QVBoxLayout(self.layoutWidget_7)
        self.verticalLayout_13.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_13.setObjectName("verticalLayout_13")
        self.label_18 = QtWidgets.QLabel(self.layoutWidget_7)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(11)
        self.label_18.setFont(font)
        self.label_18.setObjectName("label_18")
        self.verticalLayout_13.addWidget(self.label_18)
        self.ContrastSlider = QtWidgets.QSlider(self.layoutWidget_7)
        self.ContrastSlider.setMinimum(-100)
        self.ContrastSlider.setMaximum(100)
        self.ContrastSlider.setOrientation(QtCore.Qt.Horizontal)
        self.ContrastSlider.setTickPosition(QtWidgets.QSlider.NoTicks)
        self.ContrastSlider.setObjectName("ContrastSlider")
        self.verticalLayout_13.addWidget(self.ContrastSlider)
        self.layoutWidget_8 = QtWidgets.QWidget(self.Enhancement)
        self.layoutWidget_8.setGeometry(QtCore.QRect(10, 120, 311, 55))
        self.layoutWidget_8.setObjectName("layoutWidget_8")
        self.verticalLayout_14 = QtWidgets.QVBoxLayout(self.layoutWidget_8)
        self.verticalLayout_14.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_14.setObjectName("verticalLayout_14")
        self.label_19 = QtWidgets.QLabel(self.layoutWidget_8)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(11)
        self.label_19.setFont(font)
        self.label_19.setObjectName("label_19")
        self.verticalLayout_14.addWidget(self.label_19)
        self.SaturationSlider = QtWidgets.QSlider(self.layoutWidget_8)
        self.SaturationSlider.setMinimum(-100)
        self.SaturationSlider.setMaximum(100)
        self.SaturationSlider.setOrientation(QtCore.Qt.Horizontal)
        self.SaturationSlider.setTickPosition(QtWidgets.QSlider.NoTicks)
        self.SaturationSlider.setObjectName("SaturationSlider")
        self.verticalLayout_14.addWidget(self.SaturationSlider)
        self.widget2 = QtWidgets.QWidget(self.Enhancement)
        self.widget2.setGeometry(QtCore.QRect(10, 180, 311, 113))
        self.widget2.setObjectName("widget2")
        self.verticalLayout_16 = QtWidgets.QVBoxLayout(self.widget2)
        self.verticalLayout_16.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_16.setObjectName("verticalLayout_16")
        self.label_21 = QtWidgets.QLabel(self.widget2)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(11)
        self.label_21.setFont(font)
        self.label_21.setObjectName("label_21")
        self.verticalLayout_16.addWidget(self.label_21)
        self.RcolorSlider = QtWidgets.QSlider(self.widget2)
        self.RcolorSlider.setMinimum(-100)
        self.RcolorSlider.setMaximum(100)
        self.RcolorSlider.setOrientation(QtCore.Qt.Horizontal)
        self.RcolorSlider.setTickPosition(QtWidgets.QSlider.NoTicks)
        self.RcolorSlider.setObjectName("RcolorSlider")
        self.verticalLayout_16.addWidget(self.RcolorSlider)
        self.GcolorSlider = QtWidgets.QSlider(self.widget2)
        self.GcolorSlider.setMinimum(-100)
        self.GcolorSlider.setMaximum(100)
        self.GcolorSlider.setOrientation(QtCore.Qt.Horizontal)
        self.GcolorSlider.setTickPosition(QtWidgets.QSlider.NoTicks)
        self.GcolorSlider.setObjectName("GcolorSlider")
        self.verticalLayout_16.addWidget(self.GcolorSlider)
        self.BcolorSlider = QtWidgets.QSlider(self.widget2)
        self.BcolorSlider.setMinimum(-100)
        self.BcolorSlider.setMaximum(100)
        self.BcolorSlider.setOrientation(QtCore.Qt.Horizontal)
        self.BcolorSlider.setTickPosition(QtWidgets.QSlider.NoTicks)
        self.BcolorSlider.setObjectName("BcolorSlider")
        self.verticalLayout_16.addWidget(self.BcolorSlider)
        self.widget3 = QtWidgets.QWidget(self.Enhancement)
        self.widget3.setGeometry(QtCore.QRect(10, 300, 311, 38))
        self.widget3.setObjectName("widget3")
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout(self.widget3)
        self.horizontalLayout_11.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.pushButtonFleet = QtWidgets.QPushButton(self.widget3)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(11)
        self.pushButtonFleet.setFont(font)
        self.pushButtonFleet.setObjectName("pushButtonFleet")
        self.horizontalLayout_11.addWidget(self.pushButtonFleet)
        self.pushButtonGlass = QtWidgets.QPushButton(self.widget3)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(11)
        self.pushButtonGlass.setFont(font)
        self.pushButtonGlass.setObjectName("pushButtonGlass")
        self.horizontalLayout_11.addWidget(self.pushButtonGlass)
        self.pushButtonCartoon = QtWidgets.QPushButton(self.widget3)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(11)
        self.pushButtonCartoon.setFont(font)
        self.pushButtonCartoon.setObjectName("pushButtonCartoon")
        self.horizontalLayout_11.addWidget(self.pushButtonCartoon)
        self.widget4 = QtWidgets.QWidget(self.Enhancement)
        self.widget4.setGeometry(QtCore.QRect(10, 350, 311, 38))
        self.widget4.setObjectName("widget4")
        self.horizontalLayout_25 = QtWidgets.QHBoxLayout(self.widget4)
        self.horizontalLayout_25.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_25.setObjectName("horizontalLayout_25")
        self.pushButtonSmooth = QtWidgets.QPushButton(self.widget4)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(11)
        self.pushButtonSmooth.setFont(font)
        self.pushButtonSmooth.setObjectName("pushButtonSmooth")
        self.horizontalLayout_25.addWidget(self.pushButtonSmooth)
        self.pushButtonThin = QtWidgets.QPushButton(self.widget4)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(11)
        self.pushButtonThin.setFont(font)
        self.pushButtonThin.setObjectName("pushButtonThin")
        self.horizontalLayout_25.addWidget(self.pushButtonThin)
        self.pushButtonWhite = QtWidgets.QPushButton(self.widget4)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(11)
        self.pushButtonWhite.setFont(font)
        self.pushButtonWhite.setObjectName("pushButtonWhite")
        self.horizontalLayout_25.addWidget(self.pushButtonWhite)
        self.widget5 = QtWidgets.QWidget(self.Enhancement)
        self.widget5.setGeometry(QtCore.QRect(10, 400, 311, 26))
        self.widget5.setObjectName("widget5")
        self.horizontalLayout_26 = QtWidgets.QHBoxLayout(self.widget5)
        self.horizontalLayout_26.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_26.setObjectName("horizontalLayout_26")
        self.label_46 = QtWidgets.QLabel(self.widget5)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(11)
        self.label_46.setFont(font)
        self.label_46.setObjectName("label_46")
        self.horizontalLayout_26.addWidget(self.label_46)
        self.RedLipSlider = QtWidgets.QSlider(self.widget5)
        self.RedLipSlider.setMinimum(0)
        self.RedLipSlider.setMaximum(10)
        self.RedLipSlider.setOrientation(QtCore.Qt.Horizontal)
        self.RedLipSlider.setTickPosition(QtWidgets.QSlider.NoTicks)
        self.RedLipSlider.setObjectName("RedLipSlider")
        self.horizontalLayout_26.addWidget(self.RedLipSlider)
        self.toolBox.addItem(self.Enhancement, "")
        self.Feature = QtWidgets.QWidget()
        self.Feature.setGeometry(QtCore.QRect(0, 0, 331, 541))
        self.Feature.setObjectName("Feature")
        self.pushButtonFind = QtWidgets.QPushButton(self.Feature)
        self.pushButtonFind.setGeometry(QtCore.QRect(90, 20, 161, 36))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(11)
        self.pushButtonFind.setFont(font)
        self.pushButtonFind.setObjectName("pushButtonFind")
        self.widget6 = QtWidgets.QWidget(self.Feature)
        self.widget6.setGeometry(QtCore.QRect(90, 70, 161, 41))
        self.widget6.setObjectName("widget6")
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout(self.widget6)
        self.horizontalLayout_9.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.label_20 = QtWidgets.QLabel(self.widget6)
        self.label_20.setObjectName("label_20")
        self.horizontalLayout_9.addWidget(self.label_20)
        self.CntspinBox = QtWidgets.QSpinBox(self.widget6)
        self.CntspinBox.setObjectName("CntspinBox")
        self.horizontalLayout_9.addWidget(self.CntspinBox)
        self.textBrowser = QtWidgets.QTextBrowser(self.Feature)
        self.textBrowser.setGeometry(QtCore.QRect(15, 361, 301, 171))
        self.textBrowser.setObjectName("textBrowser")
        self.widget7 = QtWidgets.QWidget(self.Feature)
        self.widget7.setGeometry(QtCore.QRect(90, 110, 161, 241))
        self.widget7.setObjectName("widget7")
        self.verticalLayout_15 = QtWidgets.QVBoxLayout(self.widget7)
        self.verticalLayout_15.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_15.setObjectName("verticalLayout_15")
        self.pushButtonCenter = QtWidgets.QPushButton(self.widget7)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(11)
        self.pushButtonCenter.setFont(font)
        self.pushButtonCenter.setObjectName("pushButtonCenter")
        self.verticalLayout_15.addWidget(self.pushButtonCenter)
        self.pushButtonRect = QtWidgets.QPushButton(self.widget7)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(11)
        self.pushButtonRect.setFont(font)
        self.pushButtonRect.setObjectName("pushButtonRect")
        self.verticalLayout_15.addWidget(self.pushButtonRect)
        self.pushButtonMiniRect = QtWidgets.QPushButton(self.widget7)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(11)
        self.pushButtonMiniRect.setFont(font)
        self.pushButtonMiniRect.setObjectName("pushButtonMiniRect")
        self.verticalLayout_15.addWidget(self.pushButtonMiniRect)
        self.pushButtonCircle = QtWidgets.QPushButton(self.widget7)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(11)
        self.pushButtonCircle.setFont(font)
        self.pushButtonCircle.setObjectName("pushButtonCircle")
        self.verticalLayout_15.addWidget(self.pushButtonCircle)
        self.pushButtonTri = QtWidgets.QPushButton(self.widget7)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(11)
        self.pushButtonTri.setFont(font)
        self.pushButtonTri.setObjectName("pushButtonTri")
        self.verticalLayout_15.addWidget(self.pushButtonTri)
        self.toolBox.addItem(self.Feature, "")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(10, 10, 971, 781))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.OkButton = QtWidgets.QPushButton(self.centralwidget)
        self.OkButton.setGeometry(QtCore.QRect(1200, 10, 111, 41))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(12)
        self.OkButton.setFont(font)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/ok/icons/check.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.OkButton.setIcon(icon2)
        self.OkButton.setObjectName("OkButton")
        self.CancelButton = QtWidgets.QPushButton(self.centralwidget)
        self.CancelButton.setGeometry(QtCore.QRect(1040, 10, 111, 41))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(12)
        self.CancelButton.setFont(font)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/ok/icons/error.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.CancelButton.setIcon(icon3)
        self.CancelButton.setObjectName("CancelButton")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1346, 29))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.toolBar = QtWidgets.QToolBar(MainWindow)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(12)
        self.toolBar.setFont(font)
        self.toolBar.setStyleSheet("")
        self.toolBar.setObjectName("toolBar")
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBar)
        self.OpenAction = QtWidgets.QAction(MainWindow)
        self.OpenAction.setObjectName("OpenAction")
        self.SaveAction = QtWidgets.QAction(MainWindow)
        self.SaveAction.setObjectName("SaveAction")
        self.UndoAction = QtWidgets.QAction(MainWindow)
        self.UndoAction.setObjectName("UndoAction")
        self.RedoAction = QtWidgets.QAction(MainWindow)
        self.RedoAction.setObjectName("RedoAction")
        self.actionCamera = QtWidgets.QAction(MainWindow)
        self.actionCamera.setObjectName("actionCamera")
        self.toolBar.addAction(self.OpenAction)
        self.toolBar.addAction(self.SaveAction)
        self.toolBar.addAction(self.UndoAction)
        self.toolBar.addAction(self.RedoAction)
        self.toolBar.addAction(self.actionCamera)

        self.retranslateUi(MainWindow)
        self.toolBox.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "图像美化系统"))
        self.label_2.setText(_translate("MainWindow", "高斯噪声："))
        self.label_3.setText(_translate("MainWindow", "均匀噪声："))
        self.label_11.setText(_translate("MainWindow", "伽马噪声："))
        self.label_12.setText(_translate("MainWindow", "指数噪声："))
        self.label_14.setText(_translate("MainWindow", "中值滤波："))
        self.label.setText(_translate("MainWindow", "椒盐噪声："))
        self.label_6.setText(_translate("MainWindow", "瑞利噪声："))
        self.label_13.setText(_translate("MainWindow", "均值滤波："))
        self.label_15.setText(_translate("MainWindow", "双边滤波："))
        self.label_16.setText(_translate("MainWindow", "高斯滤波："))
        self.toolBox.setItemText(self.toolBox.indexOf(self.NosieFilter), _translate("MainWindow", "噪声与滤波"))
        self.label_17.setText(_translate("MainWindow", "旋转："))
        self.pushButtonCut.setText(_translate("MainWindow", "裁剪"))
        self.pushButtonFrame.setText(_translate("MainWindow", "添加相框"))
        self.pushButtonUpDown.setText(_translate("MainWindow", "上下翻转"))
        self.pushButtonHmerge.setText(_translate("MainWindow", "横向拼接"))
        self.pushButtonLeftRight.setText(_translate("MainWindow", "左右翻转"))
        self.pushButtonVmerge.setText(_translate("MainWindow", "纵向拼接"))
        self.label_26.setText(_translate("MainWindow", "行数："))
        self.label_27.setText(_translate("MainWindow", "列数："))
        self.pushButton4Merge.setText(_translate("MainWindow", "栅格拼接"))
        self.toolBox.setItemText(self.toolBox.indexOf(self.GeoTrans), _translate("MainWindow", "图像变换"))
        self.label_4.setText(_translate("MainWindow", "亮度："))
        self.label_18.setText(_translate("MainWindow", "对比度："))
        self.label_19.setText(_translate("MainWindow", "饱和度："))
        self.label_21.setText(_translate("MainWindow", "RGB："))
        self.pushButtonFleet.setText(_translate("MainWindow", "流年滤镜"))
        self.pushButtonGlass.setText(_translate("MainWindow", "毛玻璃滤镜"))
        self.pushButtonCartoon.setText(_translate("MainWindow", "卡通滤镜"))
        self.pushButtonSmooth.setText(_translate("MainWindow", "磨皮"))
        self.pushButtonThin.setText(_translate("MainWindow", "瘦脸"))
        self.pushButtonWhite.setText(_translate("MainWindow", "美白"))
        self.label_46.setText(_translate("MainWindow", "红唇："))
        self.toolBox.setItemText(self.toolBox.indexOf(self.Enhancement), _translate("MainWindow", "图像增强与美颜"))
        self.pushButtonFind.setText(_translate("MainWindow", "寻找轮廓"))
        self.label_20.setText(_translate("MainWindow", "轮廓序号："))
        self.textBrowser.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'SimSun\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">点击寻找轮廓后通过鼠标左键在弹出图片框中标记物体，通过鼠标右键标记背景，可实时调整至满意后按空格键退出。</p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.pushButtonCenter.setText(_translate("MainWindow", "重心标出"))
        self.pushButtonRect.setText(_translate("MainWindow", "垂直外接矩形"))
        self.pushButtonMiniRect.setText(_translate("MainWindow", "最小外接矩形"))
        self.pushButtonCircle.setText(_translate("MainWindow", "外接圆"))
        self.pushButtonTri.setText(_translate("MainWindow", "外接三角形"))
        self.toolBox.setItemText(self.toolBox.indexOf(self.Feature), _translate("MainWindow", "图像分割与特征"))
        self.OkButton.setText(_translate("MainWindow", "确认"))
        self.CancelButton.setText(_translate("MainWindow", "取消"))
        self.toolBar.setWindowTitle(_translate("MainWindow", "toolBar"))
        self.OpenAction.setText(_translate("MainWindow", "打开"))
        self.OpenAction.setShortcut(_translate("MainWindow", "Ctrl+O"))
        self.SaveAction.setText(_translate("MainWindow", "保存"))
        self.SaveAction.setShortcut(_translate("MainWindow", "Ctrl+S"))
        self.UndoAction.setText(_translate("MainWindow", "撤销"))
        self.UndoAction.setShortcut(_translate("MainWindow", "Ctrl+Z"))
        self.RedoAction.setText(_translate("MainWindow", "重做"))
        self.RedoAction.setShortcut(_translate("MainWindow", "Ctrl+Shift+Z"))
        self.actionCamera.setText(_translate("MainWindow", "拍照"))
import Resource_rc
